#!/bin/sh; C:/Program Files/Git/bin/sh.exe

INPUT_FILE=$1
MSG=$(head -n1 $INPUT_FILE)

if [[ $MSG =~ [ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎ] ]]; then
    echo "Please use english for your commit message"
    exit 1
fi
exit 0
