#!/usr/bin/env bash

INPUT_FILE=$1
MSG=$(head -n1 $INPUT_FILE)

if [[ $MSG =~ [^0-9A-Za-z\-\"\'_] ]]; then
    if [[ ! $MSG =~ [-\"\'_] ]]; then
        echo "Please use english for your commit message"
        exit 1
    fi
fi
exit 0
