#!/bin/sh; C:/Program\ Files/Git/bin/sh.exe

STAGED_FILES=$(git diff-index --cached --name-only HEAD | grep *.py)

if [ $(echo $STAGED_FILES | wc -w) -gt 0 ]; then
	python -m flake8 $STAGED_FILES
	if [ $? != 0 ]; then
		echo
		echo "Please revise above corrections before you commit"
		exit 1
	else:
		exit 0
	fi
fi
exit 0
