#!/bin/sh; C:/Program Files/Git/bin/sh.exe

CURRENT_BRANCH=$(git symbolic-ref HEAD)

IS_MASTER=$(echo $CURRENT_BRANCH | grep master | wc -l)
IS_DEVELOP=$(echo $CURRENT_BRANCH | grep develop | wc -l)

if [ $IS_MASTER -gt 0 ]; then
    echo 'You cannot to push directly to master branch'
    exit 1
elif [ $IS_DEVELOP -gt 0 ]; then
    read -p 'You are about to push "develop". Is that really what you
    want? [y|n] ' -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
        python -m unittest
        exit 0
    fi
    echo 'Aborting...'
    exit 1
fi
python -m unittest
exit 0
