#!/usr/bin/env python
import sys

from flake8.main import git


if __name__ == '__main__':
    result = git.hook(strict=True, lazy=False,)
    if result:
        print("\nPlease revise above corrections before you commit")
    sys.exit(result)
