__title__ = "pymodi"
__version__ = "1.1.0"
__author__ = "LUXROBO"
__email__ = "tech@luxrobo.com"
__description__ = "Python API for controlling modular electronics, MODI."
__url__ = "https://github.com/LUXROBO/pymodi"
__license__ = "MIT"
__summary__ = "Python API for controlling modular electronics, MODI."
